### ISSUE TITLE
Docking - closing a named pane from context menu

### ISSUE THREAD

**Issue by pavel-ch** [ControlSystemStudio/phoebus#1361]
Currently, when trying to close an empty named pane from the context menu, nothing happens. The pane must be renamed to an empty name and then closed.
I have added a confirmation dialog to enable user to close the named pane directly.
PR follows.

**Comment by kasemir** [comment]
If you create a layout with named panes, I assume you do that because you plan to display content there, so the pane needs to remain available. In practice, you would thus also "lock" that pane, and the issue you describe shouldn't arise. But OK, a dialog is certainly better than simply ignoring the close request, so go ahead.

**Comment by pavel-ch** [comment]
Thanks.
