### ISSUE TITLE
Spaces in paths&names

### ISSUE THREAD

**Issue by DorianHas** [ControlSystemStudio/phoebus#1435]
Hello there,

We encounter an issue with Phoebus recent version. Spaces in names and directories aren't took into account. It's creating the following error message : 

![errorFileBrowser](https://user-images.githubusercontent.com/51746537/88774591-ec15e400-d183-11ea-83cd-379084a2e16a.png)

Dorian

**Comment by kasemir** [comment]
Long story short: You best avoid spaces as well as characters like `(`, `)`, `:` in file names, or come up with a perfect rewrite of everything that works for everybody.

In the end, the resource names must be URIs. We need to support access to the same `display.bob` or `plot.plt` no matter if it's a local `file://path/to/plot.plt`, which is typically the case in a control room, or if it's accessed as `http://my.site.org/display_files/path/to/plot.plt`, which is often the case when users run the tool in their office. Inside a URL, spaces need to be escaped as `%20`. The technical difficulty is that when we write files, like from a display editor or the data browser, that's of course only possible with local files, not via URIs, which are read-only. So we do need to do a certain amount of conversion between URI and local files. Our code has undergone several simplifications to move from string manipulations to basic Java URI/Path/.. API, but it's tricky because for example Windows uses different file name rules than Mac OS and Linux.

**Comment by kasemir** [comment]
The problem was introduced in #1422, and I think I've found a work around that'll again allow spaces in names.

**Comment by kasemir** [comment]
Fixed
