### ISSUE TITLE
dependabot PR's

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1606]
As everyone might have noticed we have a ton of PR's created by github helping up keep our dependencies up to date.
All the PR's are of the same nature. They are updating a single dependency junit, from 4.12 to 4.13.1

1. This change is trivial and I think it might be OK if we accept them...but I will be fine if we decide to reject them too.

However we have another questions to resolve.

2. Should we opt out of the github depandbot?
I think it might be useful to have warning and such on the github page... but I am not so sure about automatic PR's

**Comment by kasemir** [comment]
Yes, I think we should update junit.
But instead of just accepting those per-pom updates, I think we should
1) Define a version property for junit, mocking, hamcrest, .. in the parent pom
2) Check if they work together, note comments in https://github.com/ControlSystemStudio/phoebus/blob/5ca634fd2325a55dc4360d6b94a69f0dc99ecbe5/dependencies/phoebus-target/pom.xml#L62
3) Then use those properties in the individual poms.

**Comment by kasemir** [comment]
I'm OK with keeping dependabot enabled, but there may be times where we acknowledge, create a ticket like #1409 to follow up later, and for now ignore it.
Or need to put it some more work beyond just accepting, as I think is required for Junit

**Comment by shroffk** [comment]
> Define a version property for junit, mocking, hamcrest, .. in the parent pom

 +1 I strongly prefer this way to taking a more concerted effort towards curating dependencies.

**Comment by shroffk** [comment]
I have disabled the dependabot auto PR feature.
We still can use the verification and should periodically update the dependencies.
