### ISSUE TITLE
MacroizedWidgetProperty.setSpecification and firePropertyChange

### ISSUE THREAD

**Issue by krisztianloki** [ControlSystemStudio/phoebus#1627]
If in `MacroizedWidgetProperty.setSpecification()` the new specification contains macros then `value` is set to `null` and `firePropertyChange()` is called with `null`. This upsets `PictureRepresentation.contentChanged()` because it expects a non-null `new_value`.
Should this be fixed in
-  `PictureRepresentation`
- or `setSpecification()` should try to expand macros
- or `firePropertyChange()` should be called with `specification` as the new value?

**Comment by kasemir** [comment]
PictureRepresentation.

The MacroizedWidgetProperty has always behaved this way, it's mentioned in the comment
```
// If specification contains macros,
// clear value so that it can be evaluated
// later, presumably once the macro values
// have been provided.
```

At the time when setSpecification is called, it may not be too early to resolve the macro because the widget is being loaded and doesn't have a parent, yet, or the macro will come from the parent of an embedded display etc.
That's why the value is set to null, so later, at runtime, it gets resolved once the widget is in its final location within the widget tree.
