### ISSUE TITLE
Alarm server argument ordering for configuration import

### ISSUE THREAD

**Issue by jacquelinegarrahan** [ControlSystemStudio/phoebus#1729]
Importing a new configuration fails if the -import argument precedes the -config argument. 

<img width="887" alt="Screen Shot 2021-01-12 at 1 38 30 PM" src="https://user-images.githubusercontent.com/25035114/104377878-f92d5200-54db-11eb-9570-b1fd58714e10.png">

**Comment by kasemir** [comment]
Yes, because `-import` actually performs that action with the information known at the time, i.e. -config needs to set the name, and maybe -server needs to set a remote URL before then using those settings with -import.

This does match the order in which the `-help` info lists the options, where '-import' is mentioned quite late and so far that seems to have guided every user to success.

If you want to make the command line option handling more robust by for example having -import just set some `import_requested` flag and then handle that after all the options have been processed, go ahead.
