### ISSUE TITLE
develop specific widget 

### ISSUE THREAD

**Issue by CC-g2ca** [ControlSystemStudio/phoebus#1741]
Hi there, we are working to add a specific widget to our version. 

our widget listens many PV and we haven't figured out how to listen to all these PV and get their values ​​back.

can you help us !

**Comment by kasemir** [comment]
In your widget model, you need some properties to hold those PV names. You also need _runtime_ properties for the values of those PVs. In the display editor, you configure the PV names, the _runtime_ properties are not shown because they're only used internally at runtime.

In your widget runtime, you then connect to those PVs (see https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/runtime/src/test/java/org/csstudio/display/builder/runtime/test/PVFactoryTest.java) and update the _runtime_ properties of the widget with the values of the PVs.

In your widget representation, you update the widget on the screen based on the values of all the properties as desired.

**Comment by CC-g2ca** [comment]
thanks
