### ISSUE TITLE
xyplot print not present

### ISSUE THREAD

**Issue by amienc** [ControlSystemStudio/phoebus#2222]
I am trying to print my 'xyplot' from the dropdown but it prints the whole screen.
I'm using Phoebus version (master 2022-04-08 03:51)

**Comment by kasemir** [comment]
Printing, and I mean it in the best possible way, sucks, because the API for printing eventually calls down into some operating system level where it's then stuck for various reasons:

 * https://github.com/ControlSystemStudio/phoebus/issues/1352
 * https://github.com/ControlSystemStudio/cs-studio/issues/356
 * https://github.com/ControlSystemStudio/cs-studio/issues/1352
 * https://github.com/ControlSystemStudio/cs-studio/issues/1937

Even if printing succeeds as far as software is concerned, the behavior of printers themselves is nicely summarized by this article in the new york times/wirecutter: 
https://www.nytimes.com/wirecutter/blog/why-all-printers-suck-even-the-best-ones/

But sure, it should be fairly easy to add another print option to the context menu of plot widgets, so I'll look into that.
