### ISSUE TITLE
Tab alignment in Tabs widget

### ISSUE THREAD

**Issue by Amadrath** [ControlSystemStudio/phoebus#2238]
When changing the parameter "Direction" in the tabs widget, the text alignment of existing tab-labels does not change, but new tabs do. As the first tab can never be "new", the text alignment can not be changed for all tabs, which results in tab-labels with a mix of vertical and horizontal text alignments.
I would propose, to expand the properties of the tab widget to have one property "Label Text Alignment" with the options vertical and horizontal, and one property "Tab Position" with the options top, bottom, left and right. This would also add the option for right and bottom aligned tabs. The property "Tab height" should depend on text alignment, because the other dimension should be derived from the font size.

**Comment by kasemir** [comment]
The tab text is roughly centered.
In the editor, "direction" can be changed.
Runtime changes of the direction as well as adding/removing tabs is not supported.
Related to runtime changes not being supported, this can sometimes lead to slightly misplaced labels while in the editor, see 'refreshHack' and 'sandbox.TabDemo'.

![Screen Shot 2022-05-06 at 8 48 59 AM](https://user-images.githubusercontent.com/1932421/167134500-cd6c01a6-2b9c-4068-8eb0-d43a3e7a5f51.png)

Changing direction:

![Screen Shot 2022-05-06 at 8 49 13 AM](https://user-images.githubusercontent.com/1932421/167134503-6a5d5276-68d4-4add-9eb5-ca544ea08445.png)

Adding new tab in editor where label is initially poorly rendered:

![Screen Shot 2022-05-06 at 8 59 28 AM](https://user-images.githubusercontent.com/1932421/167136315-4ebda3f4-adb7-4c83-861a-136a956f419a.png)

"Fixes itself" after slight resize or saving & reopening or just waiting:

![Screen Shot 2022-05-06 at 8 59 56 AM](https://user-images.githubusercontent.com/1932421/167136318-1badbe77-6579-4455-90a3-7415b847f632.png)

I'm hesitant to add options for individual label text alignment, tab position etc. because they would have to be maintained in the web runtime as well and then in the next display tool.
The basic design principle of the display builder is to have a tool for control system displays with longevity in mind, supporting a fairly generic display file format, see
https://github.com/ControlSystemStudio/phoebus/wiki/Display-Builder-Compatibility . Exact control of the pixel position of each tab's label is a very low priority

**Comment by Amadrath** [comment]
I see my misunderstanding. I assumed the new tabs would keep their horizontally aligned text. But after a reload the text is aligned vertically, like the other tabs:
![Tab_misalignedText](https://user-images.githubusercontent.com/40169401/167140931-9547b83a-bdb8-4ec4-a08a-b7127ea69c4e.png)–Reload–>![Tab_settledText](https://user-images.githubusercontent.com/40169401/167140980-8aa1b2fa-8090-445c-9ae9-798c78ccdb5d.png)

Regrettably, that does not solve my initial problem. I want to have a tab widget, which is no more than 80px high and contains 3 widgets 20px high on top of each other. So there is no room for the tabs on top. With vertical text, there is no room on the side, either. But it would work with horizontal text, like this:
![SkizzeTabs](https://user-images.githubusercontent.com/40169401/167145438-3e138e5c-8b14-44f4-9fdc-ac8370fea32c.png)

In order to maintain backwards compatibility, I would suggest to keep the existing parameter as is, and add an additional binary parameter "Flip Text Alignment", which changes the alignment of the text from the usual behaviour to the other one. If the parameter is missing in a bob-file, it defaults to the current behaviour. This would preserve backwards-compatibality

**Comment by Amadrath** [comment]
I pondered that option, but I think, switching to a widget with a different function to compensate for the lack in flexibility of the initial widget, should be a last resort.
I might also simply put all those widgets in a separate display, called by a button.
While all those options would solve, or at least shift, my immediate problem, the usability of the tab widget remains limited. Thus I would still argue, that the tab widget should be extended, at least in the long run.

**Comment by Amadrath** [comment]
I pondered that option, but I think, switching to a widget with a different function to compensate for the lack in flexibility of the initial widget, should be a last resort.
I ended up simply putting those widgets into a separate display, called by a button on the initial display. I basically split one crowded display into two similar, but less crowded, displays.
While all those options would solve, or at least shift, my immediate problem, the usability of the tab widget remains limited. Thus I would still argue, that the tab widget should be extended, in the long run.

**Comment by Amadrath** [comment]
I ended up splitting the crowded display into two, one of which can be opened from the other. This allows me to hide some of the less used widgets.

**Comment by kasemir** [comment]
Simplifying the display is always best. I won't find the time to add more options to the different types of tabs and maintain them in both the desktop and web runtime. If you do need full control over the exact look, consider building your own python display (see PyDM etc)
