### ISSUE TITLE
Detached windows' z index re-arranged

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2291]
I have a user reporting that overlapping (detached) windows will change z order after closing a model dialog. This was reported on Linux, but is easily reproduced on Mac OS. All on JavaFX 18 and JDK 11.

Found the following (old) post: https://bugs.openjdk.org/browse/JDK-8089397, which is in line with my user's problem description.

The problem is not reproducible using JDK 17 runtime.

**Comment by kasemir** [comment]
The bug report mentions "with an owner that is not the last opened window then when it closes a the last opened window will be brought to the front rather than the closed window's owner".

We have this commit to specifically set the owner of dialogs to the 'parent' window, with a comment "..to get the right dialog icons on Windows":

54fd0f668c68089c540f98ce84de09297778f8fe

If you can reproduce the issue, maybe try if removing that `initOwner` call helps, but overall this seems to be an internal issue over which we have little control.

**Comment by kasemir** [comment]
If JDK 17 and higher indeed fix the problem, then that's a perfect solution.

**Comment by georgweiss** [comment]
More testing is needed, of course, but I agree.
Unfortunately ESS cannot switch to Java 17 as target workstations' OS (CentOS 7) must be updated first.

**Comment by georgweiss** [comment]
Actually... the ``initOwner`` fix will maintain the owner window in the front, but if multiple detached and overlapping windows are used, then those other windows may still be re-arranged. And this is unfortunately not solved by running under Java 17.

**Comment by georgweiss** [comment]
Closing this as upon further testing I find Java 17 does not solve the issue originally reported by my user. JavaFX 19ea does not fix the issue either.
