### ISSUE TITLE
Stripchart Y axis doesn't follow foreground color

### ISSUE THREAD

**Issue by tynanford** [ControlSystemStudio/phoebus#2400]
The stripchart Y axis seems to be hard coded to be black and can't be changed via the properties panel

![image](https://user-images.githubusercontent.com/38359458/192881426-c9b6f17f-6a01-4ae2-83ed-efbef7984b9b.png)

I tried out fixing this and this change below seems to fix it but I have no idea if that is the right way to go about this.

https://github.com/tynanford/phoebus/commit/2195098807d39a8ee2db4007616952f9ed0b62fa

**Comment by kasemir** [comment]
The underlying RTPlot supports individual colors for each axis, and the Data Browser allows configuring those.
The stripchart already supports several Y axes, so in principle you could add a color property to each Y axis.
But since the stripchart is supposed to be a simplified data browser type of plot, I like the idea of applying the one "foreground" color to the labels, X axis and all Y axes.
So go ahead with what you already prepared.
