### ISSUE TITLE
PVA: Decode "boolean"

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#2410]
IOCs will handle "boolean" records like bi and bo as enum data types:

```
epics:nt/NTEnum:1.0
    enum_t value (0) OK
        int index 0
        string[] choices [OK, Error]
```

A custom PVA server might send "boolean" data like this:
```
epics:nt/NTScalar:1.0
     boolean value false
     alarm_t alarm [NO_ALARM]
         int severity 0
         int status 0
         string message
     time_t timeStamp [2022-10-05 16:23:26.000318114]
         long secondsPastEpoch 1664979806
         int nanoseconds 318114
         int userTag 0
```

While IOCs don't create this data type and we cannot handle any arbitrary data structure in a generic client, we should try to allow using such "boolean" values in for example an LED or bool button widget.

**Comment by hjunkes** [comment]
Thanks Kay,
our structure on the IOC looks like this, already longer ;-)

(base) hactar:natview_V3.3 junkes$ pvget FHIFEL:3gigamp_1
FHIFEL:3gigamp_1 structure
    boolean ITLK false
    boolean TRIG false
    boolean PWR false
    boolean STAT false
    boolean TPID true
    double TAMP 27.9531
    double TLIM 49
    double STG1_SWR 1
    double STG1_FWD 0
    double STG1_REV 0
    double STG2_SWR 1
    double STG2_FWD 0
    double STG2_REV 0

Unfortunately it does not work yet to link to it e.g. with an LED. (More from William ;-))

**Comment by kingspride** [comment]
Previously, with the old phoebus version before this change, the whole display / pva service from phoebus would stop entirely until the display is closed.

now, with a bleeding-edge built version from master branch, the display function normally - except the element that should display the boolean state (an LED)

<img width="339" alt="grafik" src="https://user-images.githubusercontent.com/45198837/201071142-9e887ab7-2d99-46d7-b305-103d548bd4de.png">

looks like this.
when probing boolean fields, we still get the whole structure back instead of just the value...

<img width="427" alt="grafik" src="https://user-images.githubusercontent.com/45198837/201071477-38eff333-63ec-437e-97fe-023abdf70c13.png">

**Comment by kasemir** [comment]
Got it
