### ISSUE TITLE
Autoscaling visible region only

### ISSUE THREAD

**Issue by bsobhani** [ControlSystemStudio/phoebus#2438]
For the image widget I can enable autoscale and then it will set the min/max of the colorscale to the min/max of the raw image data.

However, if I zoom into a region (by double clicking on the numbers on the axes and changing them), the autoscale is still for the entire image, not the zoomed in part.

Is there a way to make it so that autoscale uses only the data in the zoomed in region?

**Comment by kasemir** [comment]
Misunderstood "autoscale". There's the scaling of the value range, and the scaling of the axes.
The scaling of the axes was broken. With "limits from PV" checked to auto-scale the axes, one could no longer zoom/pan, which is now fixed.
The auto-scale of the values still uses the complete image...

**Comment by kasemir** [comment]
Changing the value autoscale would be a big deal because we currently always draw the complete image and the zoom/pan is just a matter of then copying that section from the image drawn in background to the display.

Besides, changing the colors when zooming in/out seems wrong because you're changing the data.

On beamlines here, the autoscale tends to be done differently anyway. The detector histogram images tend to contain some spots with very high counts. If those determine the maximum of the color scale, the rest looks pretty much black. So the color range is determined by computing the range of values within some region of interest outside of those peaks. I believe that's done by using area detector stats plugins. That min/max range is then applied, so the peaks may actually overflow the value range, but the "rest" now becomes visible.

**Comment by bsobhani** [comment]
This is not for a detector but for a 2D image which shows the evolution of an incremental d-space plot over time. They want to zoom in and observe the movement of the various peaks over time, so the only important thing is for there to be some contrast between the maximum and minimum values of the specific peak they are zooming into, so that they can see the peak.

If there is some way in the Phoebus python scripting interface to access the data that is being displayed, it seems like it would be possible for me to add a button that calculates the max/min values of this, and set the color scale to these. But I do not know if there is a way to access this data.

**Comment by kasemir** [comment]
MIght be easiest if you update https://github.com/ControlSystemStudio/phoebus/blob/master/app/rtplot/src/main/java/org/csstudio/javafx/rtplot/internal/ImagePlot.java to first check the 'zoomed' area, then determine the value range in there, then draw.

**Comment by kasemir** [comment]
Now have an update that autoscales the value.

Example image where there are just a few value pixels for example in the bottom row, second from left portion of the detector which drive the overall autoscaling and thus result in the rest being quite featureless:

<img width="1200" alt="Screen Shot 2022-11-07 at 9 55 37 AM" src="https://user-images.githubusercontent.com/1932421/200342914-63e47299-f2cd-4b38-ba13-68cd137ce1f9.png">

Zooming in on another part of the detector, autoscaling just the visible part makes those pixels more vibrant:

<img width="1200" alt="Screen Shot 2022-11-07 at 9 55 49 AM" src="https://user-images.githubusercontent.com/1932421/200342935-e09302c0-97b5-4b9b-a97b-4442a866c671.png">

At the same time, this means that the color no longer represents any absolute value. Values for colors keep changing with the zoom/pan.

**Comment by bsobhani** [comment]
I just tried it out and I confirm it does this. Thank you!
