### ISSUE TITLE
BoolButton tooltip

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2546]
The BoolButton widget is currently incapable of showing tooltip. Reason seems to be that the tooltip is attached to the Pane where the button is contained. Hovering over the button will not trigger a onShowing event on the Pane -> tooltip is not shown. However, if the PV associated with the BoolButton is off-line, then the onShowing event is received by the Pane and the tooltip is shown.

Simplest solution seems to be to not wrap the button in a pane in BoolButtonRepresentation. 

Any reason the Button must be wrapped inside a Pane?

**Comment by kasemir** [comment]
I think the bool button is a Pane because it combines the actual button with an optional LED (circle)

**Comment by georgweiss** [comment]
Not sure I agree. The LED is provided to the Button constructor as the graphic.

**Comment by kasemir** [comment]
Since the commit mentions enablement, maybe this was about keeping the context menu active?
If there's only a button, with context menu on the button, disabling the button, as one might want to do for read-only or disconnected PVs, would really disable the JavaFX button, so no more context menu.
The pane allows adding the context menu to the pane, so button disabled still allows the context menu from the pane.

**Comment by krisztianloki** [comment]
If I remember correctly the tooltip and disabled-widgets-dont-have-context-menu issues are solved in ActionButtonRepresentation. Maybe it makes sense to try and somehow generalize and apply that to all the control widgets (I believe some of those widgets already have the fixes)

**Comment by georgweiss** [comment]
Thanks @kasemir and @krisztianloki. I will look into this.
