### ISSUE TITLE
Properly recognize unsigned data in intensity plots

### ISSUE THREAD

**Issue by daykin** [ControlSystemStudio/phoebus#2595]
We have AreaDetector-based camera feeds being rendered in Intensity plots, and instead of the incoming data being in the range [0,65535], it is instead [-32768,32767]. As a result, we need to input unusual color maps to accommodate. Is it possible to detect signedness of incoming data from Channel Access?

**Comment by kasemir** [comment]
Channel access only has signed data types.

PV Access has both signed and unsigned.

In CSS/Phoebus, you can use PV Access to look at area detector images.
If you use Channel Access, the "Image" plot has an option to treat the data as unsigned since the data would otherwise not tell us.
________________________________
From: Evan Daykin ***@***.***>
Sent: Wednesday, March 15, 2023 1:23 PM
To: ControlSystemStudio/phoebus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [ControlSystemStudio/phoebus] Properly recognize unsigned data in intensity plots (Issue #2595)


We have AreaDetector-based camera feeds being rendered in Intensity plots, and instead of the incoming data being in the range [0,65535], it is instead [-32768,32767]. As a result, we need to input unusual color maps to accommodate. Is it possible to detect signedness of incoming data from Channel Access?

**Comment by daykin** [comment]
Ah, I see that now. Thanks!
