### ISSUE TITLE
Refactor of Marcos.expandValue

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2705]
Seems #2697 has removed ```Macros.expandValue()``` and added ```Macros.expand()```. Unfortunately this affects some of our OPIs where creative developers have peeked into the Java code.

Any reason to not maintain ```expandValue``` for backwards compatibility?

**Comment by georgweiss** [comment]
> And again whoever writes scripts and has to ask for help shouldn't do it, and whoever still does write scripts must be prepared to maintain them..

Agree. But recommendations - no matter how strong and clear - have a tendency to be ignored.

**Comment by georgweiss** [comment]
I may actually suggest rename back to ```Macros.expandValue```

**Comment by kasemir** [comment]
OK, I'll do that.
That way, it'll look the same, there will be no immediate error from the scripts, but they might no longer behave as originally. That will let it sink in that those who write scripts need to maintain them, they may fail without any obvious error message.

**Comment by kasemir** [comment]
..but it was `expandValues()`, plural, right?

**Comment by georgweiss** [comment]
Not sure...

I have verified that skipping the call solves the problem for the case at hand.

**Comment by georgweiss** [comment]
It's plural

**Comment by kasemir** [comment]
It was `public void expandValues(final MacroValueProvider input) throws Exception`, now it'll be `public void expandValues(final Macros base)`.

So same name, but really needs `Macros` which can iterate the values to copy, plus then expand them, not just a value provider. So some scripts will still fail because they don't have complete Macros, and again simply skipping the call is the correct solution.

**Comment by kasemir** [comment]
Try now that there is again an `expandValues` method. Do the scripts actually work when calling that?
