### ISSUE TITLE
Show file path in display builder properties view

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2890]
I have a user request for the display builder editor: show full file path at the top of the properties panel. In some cases this (e.g. when editing embedded displays) this is information that would benefit from simpler access than right click on tab title.

Any objections?

**Comment by georgweiss** [comment]
Long file names are most easily handled by setting a overrun policy, e.g. ```new Label("whatever")..setTextOverrun(OverrunStyle.CENTER_ELLIPSIS);```

As for placement I have found four different places where a file path label could be located, see screen shot.

Please comment.

![Screenshot 2023-12-15 at 13 19 33](https://github.com/ControlSystemStudio/phoebus/assets/35602960/48304aef-eb68-4043-a4f1-4b7583fbed27)

**Comment by kasemir** [comment]
I like the pseudo-property location best:

![Screenshot 2023-12-15 at 9 08 31 AM](https://github.com/ControlSystemStudio/phoebus/assets/1932421/7cda5be1-7d99-4b85-b0c2-acdc354e22f4)

In that location, a (read-only) text field that allows copying the name fits most naturally.

Maybe drop the "File Path:" from the value, so it becomes just
```
File Path:
/that/path/to/file.bob
```

Instead of
```
File Path:
File Path: /that/path/to/file.bob
```

**Comment by kasemir** [comment]
The CENTER_ELLIPSIS style is also good. Not 100% sure if that's supported by text fields or limited to labels.
Given a choice between Label with CENTER_ELLIPSIS and (read-only) text field that allows copying the text out, I'd go with the text field. Maybe then use some right aligned format so that "/some/very/long/path/to/the/file.bob" will show "o/the/file.bob".

**Comment by georgweiss** [comment]
My intension was to make the text clickable to launch the file browser app in the file's parent folder. Right click could invoke context menu to copy file path to clipboard.

Label takes less vertical space than text field...

**Comment by kasemir** [comment]
Label then sounds good, but instead of a clickable label, I'd prefer a more obvious "..." button as used with file properties (embedded display file, ..):

![Screenshot 2023-12-15 at 9 31 37 AM](https://github.com/ControlSystemStudio/phoebus/assets/1932421/8cfa21bc-3a11-45ee-b54c-6433f9920c8c)

When we add clickable labels, we turn this into a Monkey Island type video game where users will then start to click on everything just in case there's some action hidden behind each seemingly innocent label.

**Comment by georgweiss** [comment]
Do not really agree on the proposed layout. The original request was to provide quick access to the file name. If we limit the text field width and force user to click the ... button to see the full path, then that defeats the purpose.

I'd propose to use a Label for the static "File" part, and a read-only text field using entire width of the parent.

**Comment by kasemir** [comment]
Label, using the full width is fine. Last screenshot was just about the button instead of clickable label.
Some somewhat like this:
```
File Path:
[label with path][...]
```

Label can use ellipses.
The '[...]' button opens file browser.

**Comment by georgweiss** [comment]
Ah, I see what you mean. I'm fine with that.
