### ISSUE TITLE
Editing multi-line text boxes 

### ISSUE THREAD

**Issue by tanvi-ashwarya** [ControlSystemStudio/phoebus#2980]
Editing multi-line text boxes doesn’t handle newlines when editing “in-place” (double click on the text box to edit in the main editor view).  Newlines are removed and cannot be recovered.

On display:
 
![image](https://github.com/ControlSystemStudio/phoebus/assets/7050259/1a094cb7-e252-4a97-b839-14c932b7d1e1)

Editor:
 
![image](https://github.com/ControlSystemStudio/phoebus/assets/7050259/b036a674-04f2-41b3-9c29-9e7f37b58002)

Editor after double-click to change the text, newlines are immediately lost, and it is updated without newlines.
 
![image](https://github.com/ControlSystemStudio/phoebus/assets/7050259/30273ddc-81d2-4a7f-b009-1fa84ee9dcdb)

![image](https://github.com/ControlSystemStudio/phoebus/assets/7050259/b55a99ab-56d4-43d3-9576-b080547a8f07)

**Comment by kasemir** [comment]
There's a related issue with the inline editor: I keep getting it into a state where it removes spaces.
Take a label that contained "Hello". Use the inline editor to change that to "Hello    world" and the result becomes "Helloworld". Not with a freshly started instance of CS-Studio, but after running for a while. No idea what makes it get into that state. When fixing the handling of newlines, maybe something obvious comes up that would explain the removal of spaces.

**Comment by kasemir** [comment]
For what it's worth, I doubt the inline editing of multi-line text was ever fully supported because typing 'Enter' would save the current text, closing the inline editor. So you could tweak the text but not add new newlines. For full editing, you always had to use the "..." button next to the text property to open a full dialog.
Still, it's reasonable to have the inline editor show the text with newlines and then allow tweaking the text. Or maybe show newlines as '\n' and convert them back when saved.

**Comment by kasemir** [comment]
The inline editor is a TextField, not a TextArea. So it was always limited to one line.
A quick workaround would be showing newlines as `\n` and replacing them back to newlines.
This does allow editing the text, adding/removing newlines, but it looks different than showing actual newlines.
For full editing, the "..." button next to the text property would still be best.

**Comment by tanviash** [comment]
Closing the ticket, fix provided by Kay.
